# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-10 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=32)),
                ('ctelphone', models.IntegerField()),
                ('car', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=64)),
                ('cost', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
                ('number', models.IntegerField()),
                ('stok', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.CharField(max_length=64)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=32)),
                ('spassword', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
                ('stelphone', models.IntegerField()),
                ('department', models.CharField(default='销售部', max_length=32)),
                ('role', models.CharField(default='salesman', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Staff'),
        ),
    ]
