# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20170510_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='stelphone',
            field=models.IntegerField(max_length=32),
        ),
    ]
