# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20170511_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ctelphone',
            field=models.CharField(max_length=32),
        ),
    ]
