# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_result_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saled', models.IntegerField(default=0)),
                ('basic', models.IntegerField()),
                ('commission', models.IntegerField()),
                ('month', models.CharField(max_length=32)),
                ('final', models.CharField(max_length=32)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Staff')),
            ],
        ),
    ]
