# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='commission',
            field=models.IntegerField(default=0),
        ),
    ]
