# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20170516_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='basic',
        ),
        migrations.AddField(
            model_name='staff',
            name='basic',
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='salary',
            name='final',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
